version: 2
updates:
- package-ecosystem: npm
  directory: "/api-docs"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/api-gateway"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/guardian-services"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/interfaces"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/ipfs-client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/logger-helper"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/logger-service"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/message-broker"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/mrv-sender"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
- package-ecosystem: npm
  directory: "/vc-modules"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: "develop"
