openapi: 3.0.0
paths:
  /analytics/report:
    get:
      operationId: AnalyticsApi_getCurrentReport
      summary: Returns the status of the current report.
      description: Returns the status of the current report.
      parameters: []
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: &ref_0
        - analytics
  /analytics/report/update:
    get:
      operationId: AnalyticsApi_updateReport
      summary: Update current report.
      description: Update current report.
      parameters: []
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /analytics/reports:
    get:
      operationId: AnalyticsApi_getReports
      summary: Returns all reports.
      description: Returns all reports.
      parameters: []
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReportDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /analytics/reports/{uuid}:
    get:
      operationId: AnalyticsApi_getReport
      summary: Returns report data by report uuid.
      description: Returns report data by report uuid.
      parameters:
        - name: uuid
          required: true
          in: path
          description: Report identifier
          schema:
            type: string
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataContainerDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /analytics/reports/{uuid}/export/csv:
    get:
      operationId: AnalyticsApi_exportToCsv
      summary: Export report data in a csv file format.
      description: Returns a csv file.
      parameters:
        - name: uuid
          required: true
          in: path
          description: Report identifier
          schema:
            type: string
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /analytics/reports/{uuid}/export/xlsx:
    get:
      operationId: AnalyticsApi_exportToXlsx
      summary: Export report data in a xlsx file format.
      description: Returns a xlsx file.
      parameters:
        - name: uuid
          required: true
          in: path
          description: Report identifier
          schema:
            type: string
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /analytics/dashboards:
    get:
      operationId: AnalyticsApi_getDashboards
      summary: Returns all dashboards.
      description: Returns all dashboards.
      parameters: []
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DashboardDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /analytics/dashboards/{id}:
    get:
      operationId: AnalyticsApi_getDashboardById
      summary: Returns dashboard by uuid.
      description: Returns dashboard by uuid.
      parameters:
        - name: id
          required: true
          in: path
          description: Dashboard identifier
          schema:
            type: string
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataContainerDTO'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorDTO'
      tags: *ref_0
  /metrics:
    get:
      operationId: MetricsApi_getMetrics
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - metrics
info:
  title: Guardian
  description: >-
    The Guardian is a modular open-source solution that includes best-in-class
    identity management and decentralized ledger technology (DLT) libraries. At
    the heart of the Guardian solution is a sophisticated Policy Workflow Engine
    (PWE) that enables applications to offer a requirements-based tokenization
    implementation.
  version: 2.17.0
  contact:
    name: API developer
    url: https://envisionblockchain.com
    email: info@envisionblockchain.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags: []
servers:
  - url: /
    description: version 1.0
components:
  schemas:
    ReportDTO:
      type: object
      properties:
        uuid:
          type: string
        root:
          type: string
        status:
          type: string
        steep:
          type: string
        type:
          type: string
        progress:
          type: number
        maxProgress:
          type: number
        error:
          type: string
      required:
        - uuid
        - root
        - status
        - steep
        - type
        - progress
        - maxProgress
        - error
    InternalServerErrorDTO:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
      required:
        - code
        - message
    RateDTO:
      type: object
      properties:
        name:
          type: string
        value:
          type: number
      required:
        - name
        - value
    ReportDataDTO:
      type: object
      properties:
        messages:
          type: number
        topics:
          type: number
        standardRegistries:
          type: number
        users:
          type: number
        policies:
          type: number
        instances:
          type: number
        modules:
          type: number
        documents:
          type: number
        vcDocuments:
          type: number
        vpDocuments:
          type: number
        didDocuments:
          type: number
        userTopic:
          type: number
        tokens:
          type: number
        fTokens:
          type: number
        nfTokens:
          type: number
        tags:
          type: number
        schemas:
          type: number
        systemSchemas:
          type: number
        revokeDocuments:
          type: number
        fTotalBalances:
          type: number
        nfTotalBalances:
          type: number
        topSize:
          type: number
        topSRByUsers:
          $ref: '#/components/schemas/RateDTO'
        topSRByPolicies:
          $ref: '#/components/schemas/RateDTO'
        topTagsByLabel:
          $ref: '#/components/schemas/RateDTO'
        topAllSchemasByName:
          $ref: '#/components/schemas/RateDTO'
        topSystemSchemasByName:
          $ref: '#/components/schemas/RateDTO'
        topSchemasByName:
          $ref: '#/components/schemas/RateDTO'
        topModulesByName:
          $ref: '#/components/schemas/RateDTO'
        topPoliciesByName:
          $ref: '#/components/schemas/RateDTO'
        topVersionsByName:
          $ref: '#/components/schemas/RateDTO'
        topPoliciesByDocuments:
          $ref: '#/components/schemas/RateDTO'
        topPoliciesByDID:
          $ref: '#/components/schemas/RateDTO'
        topPoliciesByVC:
          $ref: '#/components/schemas/RateDTO'
        topPoliciesByVP:
          $ref: '#/components/schemas/RateDTO'
        topPoliciesByRevoked:
          $ref: '#/components/schemas/RateDTO'
        topTokensByName:
          $ref: '#/components/schemas/RateDTO'
        topFTokensByName:
          $ref: '#/components/schemas/RateDTO'
        topNFTokensByName:
          $ref: '#/components/schemas/RateDTO'
        topFTokensByBalance:
          $ref: '#/components/schemas/RateDTO'
        topNFTokensByBalance:
          $ref: '#/components/schemas/RateDTO'
      required:
        - messages
        - topics
        - standardRegistries
        - users
        - policies
        - instances
        - modules
        - documents
        - vcDocuments
        - vpDocuments
        - didDocuments
        - userTopic
        - tokens
        - fTokens
        - nfTokens
        - tags
        - schemas
        - systemSchemas
        - revokeDocuments
        - fTotalBalances
        - nfTotalBalances
        - topSize
        - topSRByUsers
        - topSRByPolicies
        - topTagsByLabel
        - topAllSchemasByName
        - topSystemSchemasByName
        - topSchemasByName
        - topModulesByName
        - topPoliciesByName
        - topVersionsByName
        - topPoliciesByDocuments
        - topPoliciesByDID
        - topPoliciesByVC
        - topPoliciesByVP
        - topPoliciesByRevoked
        - topTokensByName
        - topFTokensByName
        - topNFTokensByName
        - topFTokensByBalance
        - topNFTokensByBalance
    DataContainerDTO:
      type: object
      properties:
        uuid:
          type: string
        root:
          type: string
        report:
          $ref: '#/components/schemas/ReportDataDTO'
      required:
        - uuid
        - root
        - report
    DashboardDTO:
      type: object
      properties:
        uuid:
          type: string
        root:
          type: string
        date:
          type: string
      required:
        - uuid
        - root
        - date
