swagger: "2.0"
info:
  title: Guardian API
  version: 1.0.0
host: localhost:3050
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/account/current-user:
    get:
      description: Get current user
      responses:
        200:
          description: Current user  
  
  /api/account/register:
    post:
      description: Register user
      responses:
        200:
          description: Register user 
          
  /api/account/login:
    post:
      description: Login user
      responses:
        200:
          description: Login user
          
  /api/account/get-all-users:
    get:
      description: Return all users
      responses:
        200:
          description: Return all users
          
  /api/profile/user-balance:
    get:
      description: User balance
      responses:
        200:
          description: Return user balance
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/profile/user-state:
    get:
      description: User state
      responses:
        200:
          description: Return user state
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/profile:
    get:
      description: User profile
      responses:
        200:
          description: Return user prefile
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/profile/set-hedera-profile:
    post:
      description: Set hedera profile
      responses:
        200:
          description: Return action result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/profile/get-root-authority:
    get:
      description: Root Authority users
      responses:
        200:
          description: Return Root Authority users
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/profile/set-vc-profile:
    post:
      description: Set vc profile
      responses:
        200:
          description: Return action result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/profile/random-key:
    get:
      description: Generate random key
      responses:
        200:
          description: Generate and return random key for user
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/schema/create:
    post:
      description: Create new schema
      responses:
        200:
          description: Return action result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/schema:
    get:
      description: Get all schemas
      responses:
        200:
          description: Return all schemas
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/schema/import:
    post:
      description: Import new schema
      responses:
        200:
          description: Return action result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/schema/export:
    post:
      description: Export schema
      responses:
        200:
          description: Return action result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/create:
    post:
      description: Create new token
      responses:
        200:
          description: Return action result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens:
    get:
      description: Get all tokens
      responses:
        200:
          description: Return tokens
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/user-tokens:
    get:
      description: Get tokens for user
      responses:
        200:
          description: Return tokens for user
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/associate:
    post:
      description: Associate token
      responses:
        200:
          description: Associate token
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/all-users:
    get:
      description: Get all users with role installer
      responses:
        200:
          description: Return all users with role installer
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/associate-users:
    get:
      description: Chack user state
      responses:
        200:
          description: Return token information
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/user-kyc:
    post:
      description: Set user kyc
      responses:
        200:
          description: Return token information
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/tokens/user-freeze:
    post:
      description: Set user freeze
      responses:
        200:
          description: Return token information
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/root-balance:
    get:
      description: Root balance
      responses:
        200:
          description: Return root balance
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/root-config:
    get:
      description: Get root config
      responses:
        200:
          description: Return root config
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/set-root-config:
    post:
      description: Set root config
      responses:
        200:
          description: Return operation result
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/get-vp-documents:
    get:
      description: Get vp documents
      responses:
        200:
          description: Return vp documents
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/search-vc-documents:
    post:
      description: Search vc documents
      responses:
        200:
          description: Return vc documents
        403:
          description: Have not permissions
        500:
          description: Internal server error
          
  /api/search-documents:
    get:
      description: Search documents
      responses:
        200:
          description: Return documents
        403:
          description: Have not permissions
        500:
          description: Internal server error